feat: #WB-1985, create wrapper resize media
opendigitaleducation/edifice-tiptap-playground pull request #16
Opened 2023-11-28 17:51 UTC by Headan

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

>

Ajout d'un wrapper pour resize un media

## Type of change

Ticket: #WB-1985
Lien : https://edifice-community.atlassian.net/browse/WB-1985

Please check options that are relevant.

- [x] Chore (PATCH)
- [ ] Doc (PATCH)
- [ ] Bug fix (PATCH)
- [ ] New feature (MINOR)
- [ ] Breaking change (MAJOR)

> PATCH: refactor, internal or non-breaking change which fixes an issue
>
> MINOR: non-breaking change which adds functionality
>
> MAJOR: fix or feature that would cause existing functionality to not work as expected

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

2023-12-05 12:25 UTC, Headan commented on frontend/src/styles/table.scss
> +
@ccreusat Déplacé dans edifice-bootstrap => https://github.com/opendigitaleducation/edifice-bootstrap/pull/36

2023-12-05 12:26 UTC, Headan commented on frontend/src/components/Tiptap/ImageEditMenu.tsx
@ccreusat J'ai eu un petit soucis de type du coup j'appelle BubbleMenu dans tiptap playground et je lui donne en children le nouveau composant créé dans edifice-ui

2023-12-05 13:11 UTC, ccreusat requested changes
@Headan les composant `xNodeView` sont à externaliser dans `edifice-ui/react/tiptap`. Il n'ont pas vocation à rester dans tiptap-playground.

2023-12-05 13:11 UTC, ccreusat commented on frontend/src/components/Tiptap/VideoNodeView.tsx
> +export default VideoResize;
@Headan doublon d'export > named export suffisant

2023-12-05 13:11 UTC, ccreusat commented on frontend/src/components/Tiptap/AttachmentNodeView.tsx
> +export default AttachmentView;
@Headan doublon d'export > named export suffisant

2023-12-05 13:11 UTC, ccreusat commented on frontend/src/components/Tiptap/ImageNodeView.tsx
> +export default ImageResize;
@Headan doublon d'export > named export suffisant

2023-12-06 17:42 UTC, ccreusat approved these changes

2023-12-06 17:42 UTC, merged