feat: #WB-1984, Add image editor and link to imagemenu
opendigitaleducation/edifice-tiptap-playground pull request #21
Opened 2023-12-07 17:55 UTC by nabil-mansouri

# Description

Ce commit intègre l'éditeur d'image et le branche à la barre de retouche d'image

>

## Type of change

Please check options that are relevant.

- [ ] Chore (PATCH)
- [ ] Doc (PATCH)
- [ ] Bug fix (PATCH)
- [X ] New feature (MINOR)
- [ ] Breaking change (MAJOR)

> PATCH: refactor, internal or non-breaking change which fixes an issue
>
> MINOR: non-breaking change which adds functionality
>
> MAJOR: fix or feature that would cause existing functionality to not work as expected

## Checklist:

- [X ] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my own code
- [X ] I have commented my code, particularly in hard-to-understand areas
- [X ] My changes generate no new warnings

2023-12-07 19:23 UTC, ccreusat commented on frontend/vite.config.ts
> +          `XSRF-TOKEN=${envs.VITE_XSRF_TOKEN}; Path=/`,
?

2023-12-11 08:41 UTC, ccreusat requested changes

2023-12-11 08:41 UTC, ccreusat commented on frontend/package.json
> +    "edifice-ts-client": "^1.0.0",
@nabil-mansouri peut-être regénérer le package.json avec le script `node scripts/package.cjs` car ta version de ts-client est pas bonne (1.0.0)

2023-12-11 13:20 UTC, Romu-C commented on frontend/src/components/Tiptap/Tiptap.tsx
> +            console.log(editor.isActive("custom-image"), !isImageModalOpen);
console log?

2023-12-13 07:42 UTC, nabil-mansouri commented on frontend/vite.config.ts
> +          `XSRF-TOKEN=${envs.VITE_XSRF_TOKEN}; Path=/`,
je retesterais sans mais je sais pas pk j'avais des soucis de xsrf car il ajoutait le cookie sur tout les path sauf root...

2023-12-13 07:58 UTC, merged